<table border="1" class="dataframe data">
  <thead>
    <tr style="text-align: right;">
      <th>S.No</th>
      <th>Program</th>
      <th>Year</th>
      <th>Intake</th>
      <th>Admitted</th>
      <th>LE Admitted</th>
      <th>Total Admitted</th>
      <th>Admitted %</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>B.Tech</td>
      <td>2021-22</td>
      <td>1460</td>
      <td>1240</td>
      <td>120</td>
      <td>1360</td>
      <td>84.93</td>
    </tr>
    <tr>
      <td>2</td>
      <td>B.sc</td>
      <td>2021-22</td>
      <td>200</td>
      <td>160</td>
      <td>30</td>
      <td>190</td>
      <td>80.00</td>
    </tr>
    <tr>
      <td>3</td>
      <td>B.pharm</td>
      <td>2021-22</td>
      <td>170</td>
      <td>112</td>
      <td>25</td>
      <td>137</td>
      <td>65.88</td>
    </tr>
    <tr>
      <td>4</td>
      <td>BBA</td>
      <td>2021-22</td>
      <td>70</td>
      <td>55</td>
      <td>10</td>
      <td>65</td>
      <td>78.57</td>
    </tr>
    <tr>
      <td>5</td>
      <td>B.com</td>
      <td>2021-22</td>
      <td>80</td>
      <td>54</td>
      <td>8</td>
      <td>62</td>
      <td>67.50</td>
    </tr>
    <tr>
      <td>6</td>
      <td>B.J</td>
      <td>2021-22</td>
      <td>81</td>
      <td>56</td>
      <td>12</td>
      <td>68</td>
      <td>69.14</td>
    </tr>
    <tr>
      <td>7</td>
      <td>B.A</td>
      <td>2021-22</td>
      <td>82</td>
      <td>51</td>
      <td>15</td>
      <td>66</td>
      <td>62.20</td>
    </tr>
    <tr>
      <td>8</td>
      <td>M.Tech</td>
      <td>2021-22</td>
      <td>394</td>
      <td>290</td>
      <td>50</td>
      <td>340</td>
      <td>73.60</td>
    </tr>
    <tr>
      <td>9</td>
      <td>M.Pharm</td>
      <td>2021-22</td>
      <td>79</td>
      <td>60</td>
      <td>10</td>
      <td>70</td>
      <td>75.95</td>
    </tr>
    <tr>
      <td>10</td>
      <td>MBA</td>
      <td>2021-22</td>
      <td>40</td>
      <td>25</td>
      <td>7</td>
      <td>32</td>
      <td>62.50</td>
    </tr>
    <tr>
      <td>11</td>
      <td>Ph.D</td>
      <td>2021-22</td>
      <td>123</td>
      <td>85</td>
      <td>20</td>
      <td>105</td>
      <td>69.11</td>
    </tr>
    <tr>
      <td>Total</td>
      <td></td>
      <td></td>
      <td>2779</td>
      <td></td>
      <td></td>
      <td>2495</td>
      <td>89.78</td>
    </tr>
  </tbody>
</table>
